apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: metrics-server
    meta.helm.sh/release-namespace: kube-system
  labels:
    app.kubernetes.io/instance: metrics-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/version: 0.7.2
    helm.sh/chart: metrics-server-3.12.2
  name: metrics-server-nodeport
  namespace: kube-system
spec:
  ports:
  - appProtocol: https
    name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/instance: metrics-server
    app.kubernetes.io/name: metrics-server
  type: NodePort
