apiVersion: v1
kind: Service
metadata:
  name: usermanagement-service
  labels:
    app: usermanagement-restapp
spec:
  type: NodePort
  selector:
    app: usermanagement-restapp
  ports:
    - port: 8095
      targetPort: 8095
      nodePort: 31231

