apiVersion: v1 # string
kind: Pod # string
metadata: # Dictionary
  name: nginx
  labels: # Dictionary
    name: nginx
spec: # 
  containers: #list
    - name: myapp
      image: nginx:1.27.0
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports: # list
        - containerPort: 80
