apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resource
spec:
  hard:
    cpu: "4"
    memory: "8"
    pods: "10"

# apply to specific namespace (ex: dev1 team has only use above quota for particular namespace)