apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: aws_lbc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip #instance
    service.beta.kubernetes.io/aws-load-balancer-schema: internet-facing #internal for private facing
    #service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
  selector:
    app: myapp