apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermgnt-deploy
  labels:
    app: usermgnt-restapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usermgnt-restapp
  template:
    metadata:
      labels:
        app: usermgnt-restapp
    spec:
      initContainer:
        - name: init-db
          image: busybox:1.37
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']
      containers:
        - name: usermgnt-restapp
          image: stacksimplify/kube-usermanagement-microservice:1.0.0
          ports:
            - containerPort: 8095
          env:
            - name: DB_HOSTNAME
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "usermgmt"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-password
                  key: db-password