apiVersion: v1
kind: Service
metadata: 
  name: frontend-service
  labels:
    name: frontend
    tier: frontend-app
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31222