apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: hpa-ns
spec:
  replicas: 2
  selector:
    matachLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: aputra/myapp-195:v2
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 100m
